// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// Server-safe theme access for PDF rendering.
// Next.js app routes reject React context here because this module is imported
// by the internal PDF render route. For the current invoice flow we only need
// the default PDFX theme, so the provider is a no-op and theme reads resolve
// to that shared default.

import { type DependencyList, type ReactNode } from 'react';
import { theme as defaultTheme, type PdfxTheme } from './pdfx-theme';

export interface PdfxThemeProviderProps {
  theme?: PdfxTheme;
  children: ReactNode;
}

export function PdfxThemeProvider({ children }: PdfxThemeProviderProps) {
  return <>{children}</>;
}

export function usePdfxTheme(): PdfxTheme {
  return defaultTheme;
}

/**
 * Calls factory() and returns the result.
 * The deps parameter is accepted for API compatibility with existing callers.
 */
export function useSafeMemo<T>(factory: () => T, _deps: DependencyList): T {
  return factory();
}
